Repository m-triassi/soen390-team13, pull requests merged in 2021-01, with the labels that each got.

#3 Add basic CI/CD for Laravel
  .github/workflows/laravel.yml
Labels: CI/CD

#5 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature-request---user-story.md
  .github/ISSUE_TEMPLATE/other-issue.md
Labels: documentation

#6 Expand installation documentation
  README.md
Labels: documentation

#8 Add redux store + dev tool config
  package.json
  resources/app.css
  resources/app.tsx
  resources/models/index.ts
  yarn.lock
Labels: front-end, good first issue

#34 CYC-33 Integrate cypress to repository
  cypress.json
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package.json
  yarn.lock
Labels: enhancement
