Repository m-triassi/soen390-team13, pull requests merged in 2021-04, with the labels that each got.

#152 CYC-137 Add Filter to Purchase Order Controller Index Function
  app/Http/Controllers/PurchaseOrderController.php
  tests/Feature/PurchaseOrderTest.php
Labels: backend, enhancement, testing

#162 CYC-156 Refactor sale and purchase order statuses
  app/Http/Controllers/PurchaseOrderController.php
  app/Http/Controllers/SaleController.php
  app/Models/Sale.php
  tests/Feature/SaleTest.php
Labels: backend, refactor

#164 CYC-140 Add tests for Show and Index function for SaleController
  tests/Feature/SaleTest.php
Labels: backend, testing

#169 CYC-156 Move stringToArray helper method to base Controller class
  app/Http/Controllers/Controller.php
  app/Http/Controllers/MaterialController.php
  app/Http/Controllers/PurchaseOrderItemController.php
  app/Http/Controllers/UserRoleController.php
  tests/Feature/PurchaseOrderTest.php
Labels: backend, refactor, testing

#174 CYC-156 remove fuzzy search on sale status
  app/Http/Controllers/SaleController.php
Labels: backend, refactor

#172 CYC-156 Use route middleware groups
  routes/web.php
Labels: backend, refactor

#176 CYC-157 Add payment delay to supplier
  app/Models/Supplier.php
  database/factories/SupplierFactory.php
  database/migrations/2021_04_07_042313_add_payment_delay_to_suppliers_table.php
Labels: backend, enhancement

#179 CYC-138 Add cost accessor to PurchaseOrder
  app/Models/PurchaseOrder.php
  app/Models/Sale.php
  tests/Feature/PurchaseOrderTest.php
Labels: backend, enhancement

#181 CYC-156 Add foreign key cascades to prevent need for pre-deletions
  database/migrations/2021_04_07_213152_update_foreign_key_cascades.php
Labels: backend, bug

#173 CYC-156 Remove dead functions from Observers and controllers
  app/Http/Controllers/SaleController.php
  app/Observers/InventoryItemObserver.php
  app/Observers/PurchaseOrderObserver.php
Labels: backend, enhancement, refactor

#170 Add route that allows for filtering materials
  app/Http/Controllers/AvailableMaterialController.php
  routes/web.php
  tests/Feature/AvailbleMaterialTest.php
Labels: backend, bug, testing

#171 CYC-144 Add accounts receivable module
  resources/appModules.json
  resources/components/AppContent/AppContent.tsx
  resources/components/CheckButton/CheckButton.tsx
  resources/components/CheckButton/index.ts
  resources/components/index.ts
  resources/models/index.ts
  resources/models/receivable.ts
  resources/services/index.ts
  resources/services/receivable.ts
  resources/types/index.ts
  resources/views/ReceivableList/ReceivableList.tsx
  resources/views/ReceivableList/index.ts
  resources/views/index.ts
  tests/Unit/PurchaseOrderObserverTest.php
Labels: enhancement, front-end

#182 CYC-142 Sale Module Front end
  app/Http/Controllers/SaleController.php
  app/Http/Controllers/SaleItemController.php
  app/Models/Sale.php
  database/migrations/2021_03_26_174450_create_sales_table.php
  resources/components/AppContent/AppContent.tsx
  resources/components/MaterialsTable/MaterialsTable.tsx
  resources/components/MaterialsTable/index.ts
  resources/components/SaleItemModal/SaleItemModal.tsx
  resources/components/SaleItemModal/index.ts
  resources/components/index.ts
  resources/models/index.ts
  resources/models/sale.ts
  resources/services/index.ts
  resources/services/sale.ts
  resources/types/index.ts
  resources/views/SaleList/SaleList.tsx
  resources/views/SaleList/index.ts
  resources/views/index.ts
  routes/web.php
Labels: enhancement, front-end

#185 CYC-143 Accounting payable module Front end
  app/Http/Controllers/PurchaseOrderController.php
  resources/components/AppContent/AppContent.tsx
  resources/models/order-list.ts
  resources/services/order.ts
  resources/views/PayableList/PayableList.tsx
  resources/views/PayableList/index.ts
  resources/views/index.ts
Labels: enhancement, front-end

#186 CYC-129 Add payment delay to supplier form
  resources/models/vendor.ts
  resources/views/VendorList/VendorList.tsx
Labels: enhancement, front-end

#156 CYC-122 Add vendor detail view
  .eslintrc.json
  resources/components/AppContent/AppContent.tsx
  resources/services/inventory.ts
  resources/services/vendor.ts
  resources/views/SupplierDetails/SupplierDetails.tsx
  resources/views/SupplierDetails/index.ts
  resources/views/VendorList/VendorList.tsx
  resources/views/index.ts
Labels: enhancement, front-end

#166 CYC-147 CYC-149 Front-end refactor
  .eslintrc.json
  .github/workflows/react.yml
  jest.config.js
  package.json
  resources/components/AppContent/AppContent.tsx
  resources/components/BOMForm/BOMForm.tsx
  resources/components/BasicLayout/BasicLayout.tsx
  resources/components/DeleteButton/DeleteButton.tsx
  resources/components/InventoryItemDetail/InventoryItemDetail.tsx
  resources/components/InventoryItemDetail/styleSheet.css
  resources/icons/logo.svg
  resources/services/bom-material.ts
  resources/services/inventory.ts
  resources/services/order.ts
  resources/services/setting.ts
  resources/services/vendor.ts
  resources/tests/components.test.js
  resources/tests/utils-functions.test.js
  resources/types/index.ts
  resources/utils/index.tsx
  resources/views/InventoryList/InventoryList.tsx
  resources/views/InventoryList/components/AddInventoryItemModal.tsx
  resources/views/InventoryList/components/InventoryDetailDrawer.tsx
  resources/views/InventoryList/styleSheet.css
  resources/views/OrderForm/OrderForm.tsx
  resources/views/OrderList/OrderList.tsx
  resources/views/SettingPage/SettingPage.tsx
  resources/views/SettingPage/index.ts
  resources/views/VendorList/VendorList.tsx
  resources/views/WelcomePage/WelcomePage.tsx
  resources/views/index.ts
  tsconfig.json
  webpack.mix.js
  yarn.lock
Labels: CI/CD, bug, enhancement, front-end, refactor, testing

#190 CYC-159 Generate Mock Data
  database/factories/InventoryItemFactory.php
  database/factories/SupplierFactory.php
Labels: backend, enhancement

#191 CYC-163 Fix Observer and Date format issues
  app/Http/Controllers/SupplierController.php
  app/Observers/PurchaseOrderObserver.php
  app/Observers/SaleObserver.php
  app/Providers/EventServiceProvider.php
  tests/Feature/PurchaseOrderItemTest.php
  tests/Feature/PurchaseOrderTest.php
  tests/Feature/SupplierTest.php
Labels: backend, bug, enhancement
