Repository m-triassi/soen390-team13, pull requests merged in 2021-03, with the labels that each got.

#95 CYC-106 Add Suppliers Model and migrations
  app/Http/Controllers/InventoryItemController.php
  app/Models/InventoryItem.php
  app/Models/Supplier.php
  database/factories/InventoryItemFactory.php
  database/factories/SupplierFactory.php
  database/migrations/2021_03_03_214343_create_suppliers_table.php
  database/seeders/DatabaseSeeder.php
Labels: enhancement

#96 CYC-107 CYC-110 Add Purchase Order and Orderables Models
  app/Models/OrderItem.php
  app/Models/PurchaseOrder.php
  app/Models/Supplier.php
  database/factories/PurchaseOrderFactory.php
  database/migrations/2021_03_03_224040_create_purchase_orders_table.php
  database/migrations/2021_03_03_224820_create_orderables_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/OrderableSeeder.php
Labels: enhancement

#98 CYC-112 Add Store Supplier Attach Controller function
  app/Http/Controllers/InventoryItemController.php
  app/Http/Controllers/SupplierItemController.php
  routes/web.php
  tests/Feature/SupplierItemTest.php
Labels: backend, enhancement, testing

#106 CYC-111 Add Update function to PurchaseOrderController
  app/Http/Controllers/PurchaseOrderItemController.php
  routes/web.php
  tests/Feature/PurchaseOrderItemTest.php
Labels: backend, enhancement, testing

#101 CYC-117 #99 Add Vender Index
  resources/components/AppContent/AppContent.tsx
  resources/models/index.ts
  resources/models/inventory.ts
  resources/models/vendor.ts
  resources/services/index.ts
  resources/services/vendor.ts
  resources/types/index.ts
  resources/views/VendorList/VendorList.tsx
  resources/views/VendorList/index.ts
  resources/views/index.ts
  webpack.mix.js
Labels: front-end

#108 CYC-104 Add show and index supplier controller functions
  app/Http/Controllers/SupplierController.php
  routes/web.php
  tests/Feature/SupplierTest.php
Labels: backend, enhancement

#110 CYC-114 Add observer that updates associated stock when order is fulfilled
  app/Models/PurchaseOrder.php
  app/Observers/PurchaseOrderObserver.php
  app/Providers/EventServiceProvider.php
  tests/Unit/PurchaseOrderObserverTest.php
Labels: backend, enhancement, testing

#114 CYC-112 add filter inventory items by supplier
  app/Http/Controllers/InventoryItemController.php
  tests/Feature/InventoryTest.php
Labels: backend, enhancement, testing

#113 CYC-117 #99 Add Vender Index
  resources/services/index.ts
  resources/views/VendorList/VendorList.tsx
Labels: bug, front-end

#107 CYC-115 Add missing columns to Inventory Item table
  app/Http/Controllers/InventoryItemController.php
  app/Http/Controllers/MaterialController.php
  app/Http/Controllers/PurchaseOrderItemController.php
  app/Models/InventoryItem.php
  app/Models/OrderItem.php
  app/Models/PurchaseOrder.php
  config/session.php
  database/migrations/2021_03_03_224040_create_purchase_orders_table.php
  database/migrations/2021_03_10_024337_add_quantity_to_bom.php
  database/migrations/2021_03_10_030835_add_minimum_stock_inventory_item.php
  tests/Feature/PurchaseOrderItemTest.php
Labels: backend, enhancement

#121 CYC-105 Add Store + Update Supplier Controller Functions
  app/Http/Controllers/SupplierController.php
  routes/web.php
  tests/Feature/SupplierTest.php
Labels: backend

#120 CYC-124 Fix BOM Store/Update to use Sync
  app/Http/Controllers/MaterialController.php
Labels: bug

#127 CYC-109 Add Store + Update Purchase Order Controller Functions
  app/Http/Controllers/PurchaseOrderController.php
  routes/web.php
  tests/Feature/PurchaseOrderTest.php
Labels: backend

#135 CYC-118 Add Inventory List column for supplier
  resources/views/InventoryList/InventoryList.tsx
Labels: enhancement, front-end

#137 Drawer Bug Fixes
  app/Http/Controllers/InventoryItemController.php
  resources/components/InventoryItemDetail/InventoryItemDetail.tsx
Labels: bug

#131 CYC-116 Add Observer, Auto order inventory when below min_stock
  app/Http/Controllers/InventoryItemController.php
  app/Observers/InventoryItemObserver.php
  app/Providers/EventServiceProvider.php
  database/factories/InventoryItemFactory.php
  database/migrations/2021_03_03_224040_create_purchase_orders_table.php
  tests/Feature/InventoryTest.php
  tests/Unit/InventoryItemObserverTest.php
Labels: backend, enhancement

#133 CYC-130 Add CSV Report generator and download endpoint
  app/Actions/GenerateStockCSVAction.php
  app/Console/Kernel.php
  app/Http/Controllers/StockReportController.php
  app/Mail/StockReport.php
  resources/views/emails/stock/report_plain.blade.php
  routes/web.php
  tests/Feature/StockReportTest.php
Labels: backend, enhancement

#141 Update README.md
  README.md
Labels: documentation

#142 CYC-71 CYC-73 Add BOM Creation Form Component
  resources/components/AppContent/AppContent.tsx
  resources/components/BOMForm/BOMForm.tsx
  resources/components/BOMForm/index.ts
  resources/components/InventoryItemDetail/InventoryItemDetail.tsx
  resources/components/InventoryItemDetail/styleSheet.css
  resources/components/index.ts
  resources/models/bom-material.ts
  resources/models/index.ts
  resources/models/order.ts
  resources/services/bom-material.ts
  resources/services/index.ts
  resources/services/order.ts
  resources/types/index.ts
  resources/views/InventoryList/InventoryList.tsx
  resources/views/InventoryList/components/InventoryDetailDrawer.tsx
  resources/views/InventoryList/styleSheet.css
  resources/views/OrderForm/OrderForm.tsx
  resources/views/OrderForm/index.ts
  resources/views/index.ts
Labels: enhancement, front-end

#143 CYC-120 Add pending order list module
  resources/appModules.json
  resources/components/AppContent/AppContent.tsx
  resources/models/index.ts
  resources/models/order-list.ts
  resources/models/order.ts
  resources/services/index.ts
  resources/services/order.ts
  resources/types/index.ts
  resources/views/OrderList/OrderList.tsx
  resources/views/OrderList/index.ts
  resources/views/index.ts
Labels: enhancement, front-end

#145 CYC-133 Add Sale Model and Migration
  app/Models/OrderItem.php
  app/Models/Sale.php
  database/factories/SaleFactory.php
  database/migrations/2021_03_26_174450_create_sales_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/OrderableSeeder.php
Labels: backend, enhancement

#149 CYC-139 Add Scope query to Sales to allow for filtering by status
  app/Models/Sale.php
Labels: backend, enhancement

#147 CYC-134 Add SaleController Update + Store Functions
  app/Http/Controllers/SaleController.php
  database/migrations/2021_03_26_174450_create_sales_table.php
  routes/web.php
  tests/Feature/SaleTest.php
Labels: backend, enhancement
