Repository m-triassi/soen390-team13, pull requests merged in 2021-02, with the labels that each got.

#35 CYC-35 Integrate jest to repository
  .eslintrc.json
  package.json
  yarn.lock
Labels: front-end

#37 CYC-38 CYC-39 CYC-45 Add Authentication scaffolding
  README.md
  app/Http/Controllers/Auth/AuthenticatedSessionController.php
  app/Http/Controllers/Auth/ConfirmablePasswordController.php
  app/Http/Controllers/Auth/EmailVerificationNotificationController.php
  app/Http/Controllers/Auth/EmailVerificationPromptController.php
  app/Http/Controllers/Auth/NewPasswordController.php
  app/Http/Controllers/Auth/PasswordResetLinkController.php
  app/Http/Controllers/Auth/RegisteredUserController.php
  app/Http/Controllers/Auth/VerifyEmailController.php
  app/Http/Requests/Auth/LoginRequest.php
  app/Providers/RouteServiceProvider.php
  app/View/Components/AppLayout.php
  app/View/Components/GuestLayout.php
  composer.json
  composer.lock
  package.json
  resources/app.css
  resources/css/app.css
  resources/js/app.tsx
  resources/views/auth/confirm-password.blade.php
  resources/views/auth/forgot-password.blade.php
  resources/views/auth/login.blade.php
  resources/views/auth/register.blade.php
  resources/views/auth/reset-password.blade.php
  resources/views/auth/verify-email.blade.php
  resources/views/components/application-logo.blade.php
  resources/views/components/auth-card.blade.php
  resources/views/components/auth-session-status.blade.php
  resources/views/components/auth-validation-errors.blade.php
  resources/views/components/button.blade.php
  resources/views/components/dropdown-link.blade.php
  resources/views/components/dropdown.blade.php
  resources/views/components/input.blade.php
  resources/views/components/label.blade.php
  resources/views/components/nav-link.blade.php
  resources/views/components/responsive-nav-link.blade.php
  resources/views/dashboard.blade.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/guest.blade.php
  resources/views/layouts/navigation.blade.php
  routes/auth.php
  routes/web.php
  tailwind.config.js
  tests/Feature/AuthenticationTest.php
  tests/Feature/EmailVerificationTest.php
  tests/Feature/PasswordConfirmationTest.php
  tests/Feature/PasswordResetTest.php
  tests/Feature/RegistrationTest.php
  webpack.mix.js
  yarn.lock
Labels: enhancement

#45 Add jest unit test to CI/CD
  .github/workflows/react.yml
Labels: CI/CD, front-end

#46 CYC-86 Application basic layout
  .babelrc
  .eslintrc.json
  .gitignore
  index.d.ts
  package.json
  public/img/logo.svg
  resources/app.css
  resources/app.tsx
  resources/appModules.json
  resources/components/AppContent/AppContent.tsx
  resources/components/AppContent/index.ts
  resources/components/BasicLayout/BasicLayout.css
  resources/components/BasicLayout/BasicLayout.tsx
  resources/components/BasicLayout/index.ts
  resources/components/index.ts
  resources/models/index.ts
  resources/models/router.ts
  resources/types/index.ts
  resources/views/welcome.blade.php
  tsconfig.json
  webpack.mix.js
  yarn.lock
Labels: front-end

#50 CYC-88 Add SPA Route with Auth Middleware
  app/Providers/RouteServiceProvider.php
  resources/views/layouts/app-spa.blade.php
  resources/views/main.blade.php
  resources/views/welcome.blade.php
  routes/web.php
  tests/Feature/ExampleTest.php
Labels: enhancement

#61 CYC-64 Create InventoryItemController and update function
  app/Http/Controllers/InventoryItemController.php
  app/Http/Controllers/MaterialController.php
  app/Models/InventoryItem.php
  routes/web.php
Labels: backend, enhancement

#64 CYC-64 Add auth middleware to InventoryItemController
  routes/web.php
Labels: backend, enhancement

#65 CYC-74 add show bom controller
  app/Http/Controllers/MaterialController.php
  routes/web.php
Labels: backend, enhancement

#67 CYC-68 Add Destroy Inventory Controller function
  app/Http/Controllers/InventoryItemController.php
  database/migrations/2021_02_10_010234_create_bill_of_materials_table.php
  routes/web.php
Labels: backend, enhancement

#70 CYC-80 CYC-82 CYC-83 Add Role model, and management controller functions
  app/Http/Controllers/UserRoleController.php
  app/Models/Role.php
  app/Models/User.php
  database/migrations/2021_02_19_013328_create_roles_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/RoleSeeder.php
  routes/web.php
Labels: backend, enhancement

#78 CYC-81 Create Store Role Controller function
  app/Http/Controllers/RoleController.php
  routes/web.php
Labels: backend, enhancement

#80 CYC-75 Add Index BOM Controller function
  app/Http/Controllers/MaterialController.php
  routes/web.php
Labels: backend, enhancement

#81 CYC-72 Add Update BOM Controller function
  app/Http/Controllers/MaterialController.php
  routes/web.php
Labels: backend, enhancement

#71 CYC-60 CYC-63 Add Inventory Form Modal & Search function
  .babelrc
  app/Http/Controllers/InventoryItemController.php
  package.json
  resources/components/AppContent/AppContent.tsx
  resources/components/BasicLayout/BasicLayout.css
  resources/components/BasicLayout/BasicLayout.tsx
  resources/models/index.ts
  resources/models/inventory.ts
  resources/services/index.ts
  resources/services/inventory.ts
  resources/types/index.ts
  resources/views/InventoryList/InventoryList.tsx
  webpack.mix.js
  yarn.lock
Labels: enhancement, front-end

#85 CYC-29 Add Proper Logo to login page
  public/img/login_logo.png
  resources/views/auth/login.blade.php
  resources/views/components/application-logo.blade.php
Labels: enhancement, front-end
